apiVersion: v1
kind: Service
metadata:
  name: your-spotify-client
  namespace: your-spotify
spec:
  selector:
    app: your-spotify-client
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
